// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-cards/GradientBorder.tsx": () => import("../components/mockups/product-cards/GradientBorder.tsx"),
  "./components/mockups/product-cards/SpotlightGlow.tsx": () => import("../components/mockups/product-cards/SpotlightGlow.tsx"),
  "./components/mockups/product-cards/TiltStack.tsx": () => import("../components/mockups/product-cards/TiltStack.tsx")
};
